<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Libro de texto abierto para Econometría I en la Universidad de Granada. Combina apuntes de clase, prácticas en R y auto-evaluaciones interactivas en un único volumen reproducible.">

<title>1&nbsp; Conceptos Iniciales – Econometría I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/02-regresion-simple.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-acff971833d9769290026d534105daaa.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-conceptos-iniciales.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Conceptos Iniciales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Econometría I</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-conceptos-iniciales.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Conceptos Iniciales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-regresion-simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El Modelo de Regresión Lineal Simple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-regresion-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El Modelo de Regresión Lineal Múltiple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-inferencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inferencia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-prediccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Predicción y Selección de Modelos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-no-lineal-cualitativa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relaciones No Lineales e Información Cualitativa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-heterocedasticidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Heterocedasticidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-autocorrelacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Autocorrelación</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendice-a-prerrequisitos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Prerrequisitos matemáticos y estadísticos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendice-b-crosswalk-wooldridge-cgl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Crosswalk Wooldridge ↔︎ Carter–Griffiths–Lim</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendice-c-tablas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Tablas estadísticas</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objetivos-de-aprendizaje" id="toc-objetivos-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivos-de-aprendizaje">Objetivos de aprendizaje</a></li>
  <li><a href="#pregunta-motivadora" id="toc-pregunta-motivadora" class="nav-link" data-scroll-target="#pregunta-motivadora">Pregunta motivadora</a></li>
  <li><a href="#qué-es-la-econometría" id="toc-qué-es-la-econometría" class="nav-link" data-scroll-target="#qué-es-la-econometría"><span class="header-section-number">1.1</span> ¿Qué es la Econometría?</a></li>
  <li><a href="#el-modelo-econométrico" id="toc-el-modelo-econométrico" class="nav-link" data-scroll-target="#el-modelo-econométrico"><span class="header-section-number">1.2</span> El modelo econométrico</a></li>
  <li><a href="#usos-de-la-econometría" id="toc-usos-de-la-econometría" class="nav-link" data-scroll-target="#usos-de-la-econometría"><span class="header-section-number">1.3</span> Usos de la econometría</a></li>
  <li><a href="#correlación-no-implica-causalidad" id="toc-correlación-no-implica-causalidad" class="nav-link" data-scroll-target="#correlación-no-implica-causalidad"><span class="header-section-number">1.4</span> Correlación no implica causalidad</a>
  <ul class="collapse">
  <li><a href="#sesgo-de-selección" id="toc-sesgo-de-selección" class="nav-link" data-scroll-target="#sesgo-de-selección"><span class="header-section-number">1.4.1</span> Sesgo de selección</a></li>
  <li><a href="#sesgo-de-variable-omitida" id="toc-sesgo-de-variable-omitida" class="nav-link" data-scroll-target="#sesgo-de-variable-omitida"><span class="header-section-number">1.4.2</span> Sesgo de variable omitida</a></li>
  <li><a href="#por-qué-la-aleatorización-resuelve-el-problema" id="toc-por-qué-la-aleatorización-resuelve-el-problema" class="nav-link" data-scroll-target="#por-qué-la-aleatorización-resuelve-el-problema"><span class="header-section-number">1.4.3</span> Por qué la aleatorización resuelve el problema</a></li>
  </ul></li>
  <li><a href="#tipos-de-experimentos" id="toc-tipos-de-experimentos" class="nav-link" data-scroll-target="#tipos-de-experimentos"><span class="header-section-number">1.5</span> Tipos de experimentos</a>
  <ul class="collapse">
  <li><a href="#experimentos-aleatorizados" id="toc-experimentos-aleatorizados" class="nav-link" data-scroll-target="#experimentos-aleatorizados"><span class="header-section-number">1.5.1</span> Experimentos aleatorizados</a></li>
  <li><a href="#cuasi-experimentos" id="toc-cuasi-experimentos" class="nav-link" data-scroll-target="#cuasi-experimentos"><span class="header-section-number">1.5.2</span> Cuasi-experimentos</a></li>
  <li><a href="#datos-no-experimentales-observacionales" id="toc-datos-no-experimentales-observacionales" class="nav-link" data-scroll-target="#datos-no-experimentales-observacionales"><span class="header-section-number">1.5.3</span> Datos no experimentales (observacionales)</a></li>
  </ul></li>
  <li><a href="#tipos-de-datos-económicos" id="toc-tipos-de-datos-económicos" class="nav-link" data-scroll-target="#tipos-de-datos-económicos"><span class="header-section-number">1.6</span> Tipos de datos económicos</a></li>
  <li><a href="#práctica-exploración-de-datos-económicos-en-r" id="toc-práctica-exploración-de-datos-económicos-en-r" class="nav-link" data-scroll-target="#práctica-exploración-de-datos-económicos-en-r"><span class="header-section-number">1.7</span> Práctica: exploración de datos económicos en R</a>
  <ul class="collapse">
  <li><a href="#estructura-del-conjunto-de-datos" id="toc-estructura-del-conjunto-de-datos" class="nav-link" data-scroll-target="#estructura-del-conjunto-de-datos"><span class="header-section-number">1.7.1</span> Estructura del conjunto de datos</a></li>
  <li><a href="#estadísticas-descriptivas" id="toc-estadísticas-descriptivas" class="nav-link" data-scroll-target="#estadísticas-descriptivas"><span class="header-section-number">1.7.2</span> Estadísticas descriptivas</a></li>
  <li><a href="#distribuciones" id="toc-distribuciones" class="nav-link" data-scroll-target="#distribuciones"><span class="header-section-number">1.7.3</span> Distribuciones</a></li>
  <li><a href="#diagrama-de-dispersión-salario-frente-a-educación" id="toc-diagrama-de-dispersión-salario-frente-a-educación" class="nav-link" data-scroll-target="#diagrama-de-dispersión-salario-frente-a-educación"><span class="header-section-number">1.7.4</span> Diagrama de dispersión: salario frente a educación</a></li>
  <li><a href="#medias-condicionales" id="toc-medias-condicionales" class="nav-link" data-scroll-target="#medias-condicionales"><span class="header-section-number">1.7.5</span> Medias condicionales</a></li>
  </ul></li>
  <li><a href="#auto-evaluación" id="toc-auto-evaluación" class="nav-link" data-scroll-target="#auto-evaluación">Auto-evaluación</a></li>
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios">Ejercicios</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Conceptos Iniciales</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objetivos-de-aprendizaje" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="objetivos-de-aprendizaje">Objetivos de aprendizaje</h2>
<ul>
<li><strong>Definir</strong> qué es la econometría y distinguirla de un modelo puramente teórico.</li>
<li><strong>Identificar</strong> las dos componentes de un modelo econométrico —parte sistemática y término de error— y reconocer los parámetros desconocidos <span class="math inline">\(\beta_0, \beta_1, \ldots\)</span></li>
<li><strong>Explicar</strong> por qué correlación no implica causalidad y <strong>diagnosticar</strong> sesgo de selección y sesgo de variable omitida en ejemplos aplicados.</li>
<li><strong>Distinguir</strong> los tres grandes diseños empíricos en economía: experimentos aleatorizados, cuasi-experimentos y datos observacionales.</li>
<li><strong>Clasificar</strong> un conjunto de datos económicos como de corte transversal, de series temporales, de panel o panel agrupado.</li>
<li><strong>Explorar</strong> un conjunto de datos en R con <code>str()</code>, <code>summary()</code>, <code>head()</code>, <code>hist()</code>, <code>plot()</code> y <code>tapply()</code>, y <strong>calcular</strong> medias condicionales para detectar asociaciones brutas.</li>
</ul>
</section>
<section id="pregunta-motivadora" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="pregunta-motivadora">Pregunta motivadora</h2>
<blockquote class="blockquote">
<p><em>¿Asistir a la universidad <strong>causa</strong> mayores salarios, o las personas que de todos modos habrían ganado más tienden a ir a la universidad?</em></p>
</blockquote>
<p>A lo largo del curso veremos que responder a esta pregunta —y a muchas otras del mismo tipo— exige algo más que una simple correlación entre nivel educativo y salario. Hace falta un <strong>modelo</strong>, una <strong>muestra</strong> y, sobre todo, un <strong>diseño</strong> que nos permita atribuir las diferencias observadas a la causa que nos interesa.</p>
</section>
<section id="qué-es-la-econometría" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="qué-es-la-econometría"><span class="header-section-number">1.1</span> ¿Qué es la Econometría?</h2>
<p> <strong>econometría</strong> es la aplicación de métodos estadísticos a datos económicos con el fin de dar contenido empírico a las relaciones económicas. Su objetivo principal es la <strong>estimación</strong> y <strong>contraste</strong> de relaciones entre variables económicas. Algunos ejemplos típicos:</p>
<ul>
<li>Educación <span class="math inline">\(\Rightarrow\)</span> Salario</li>
<li>Asistencia a clase <span class="math inline">\(\Rightarrow\)</span> Nota final</li>
<li>Tasas de matrícula <span class="math inline">\(\Rightarrow\)</span> Inscripción</li>
<li>Renta <span class="math inline">\(\Rightarrow\)</span> Felicidad</li>
<li>Gasto público en seguridad <span class="math inline">\(\Rightarrow\)</span> Criminalidad</li>
<li>Publicidad <span class="math inline">\(\Rightarrow\)</span> Ventas</li>
</ul>
<p>En general nos referimos a estas variables como <span class="math inline">\(X \Rightarrow Y\)</span>, donde <span class="math inline">\(X\)</span> es la <strong>variable independiente</strong> (también llamada regresora o explicativa) e <span class="math inline">\(Y\)</span> es la <strong>variable dependiente</strong> (también respuesta o resultado). Frente a cualquier relación de este tipo surgen dos preguntas fundamentales:</p>
<ol type="1">
<li>¿<strong>Existe</strong> un efecto de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span>?</li>
<li>¿Cuál es la <strong>magnitud</strong> del efecto?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Decisores y preguntas de «¿cuánto?»
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cada día, quienes toman decisiones se enfrentan a preguntas cuantitativas:</p>
<ul>
<li>Un ayuntamiento se plantea cuánto se reducirá el crimen violento si se destina un millón de euros adicional a poner más policías en la calle.</li>
<li>El propietario de una pizzería local debe decidir cuánto invertir en publicidad digital y, por tanto, necesita estimar la relación entre publicidad y ventas.</li>
<li>Una universidad privada en Andalucía necesita estimar en cuánto disminuirá la matrícula si sube la tasa anual 300 euros.</li>
</ul>
<p>La econometría es la caja de herramientas para responder este tipo de preguntas con datos <span class="citation" data-cites="wooldridge2020">(<a href="#ref-wooldridge2020" role="doc-biblioref">Wooldridge 2020</a>)</span>.</p>
</div>
</div>
</section>
<section id="el-modelo-econométrico" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="el-modelo-econométrico"><span class="header-section-number">1.2</span> El modelo econométrico</h2>
<p>El modelo econométrico consta de <strong>dos componentes</strong>:</p>
<ol type="1">
<li><strong>La parte sistemática</strong>: el comportamiento medio de muchos individuos, empresas u observaciones.</li>
<li><strong>El error aleatorio</strong> <span class="math inline">\(u\)</span>: recoge todos los factores que afectan a <span class="math inline">\(Y\)</span> y que se han omitido en la especificación.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejemplo: determinación del salario
</div>
</div>
<div class="callout-body-container callout-body">
<p>Algunos factores asociados al salario por hora de un individuo son la edad, el género, la experiencia y la educación: <span class="math display">\[
\text{Salario} = f(\text{Edad},\ \text{Género},\ \text{Experiencia},\ \text{Educación}) + u
\]</span> Una especificación <strong>lineal</strong> sería: <span class="math display">\[
\text{Salario} = \beta_0 + \beta_1\,\text{Edad} + \beta_2\,\text{Género} + \beta_3\,\text{Experiencia} + \beta_4\,\text{Educación} + u
\]</span> Los coeficientes <span class="math inline">\(\beta_0, \beta_1, \ldots, \beta_4\)</span> son <strong>parámetros desconocidos</strong> que queremos estimar a partir de una muestra de datos y de una técnica econométrica (por ejemplo, Mínimos Cuadrados Ordinarios; véase el Capítulo 2).</p>
</div>
</div>
<p>Dos observaciones importantes:</p>
<ul>
<li>La <strong>forma funcional</strong> (lineal, log-lineal, cuadrática, …) representa una hipótesis sobre la relación entre variables. En cada problema, uno de los retos consiste en elegir una forma funcional compatible con la teoría económica y con los datos.</li>
<li>El error <span class="math inline">\(u\)</span> <strong>no es observable</strong>. Cuando estimamos el modelo en una muestra, obtenemos los <strong>residuos</strong> <span class="math inline">\(\hat{u}_i = y_i - \hat{y}_i\)</span>, que son la versión muestral —y observable— del error poblacional.</li>
</ul>
</section>
<section id="usos-de-la-econometría" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="usos-de-la-econometría"><span class="header-section-number">1.3</span> Usos de la econometría</h2>
<p>El modelo econométrico cumple tres grandes funciones, que conviene distinguir desde el principio:</p>
<ul>
<li><strong>Contrastar teorías e hipótesis económicas</strong>. Por ejemplo: ¿reduce el empleo un aumento del salario mínimo?</li>
<li><strong>Predecir variables económicas</strong>. Por ejemplo: pronosticar el crecimiento del PIB o el precio de las acciones de una empresa.</li>
<li><strong>Estimar relaciones causales</strong>. Por ejemplo: ¿un año adicional de educación <strong>causa</strong> un salario más alto, ceteris paribus?</li>
</ul>
<p>El tercer punto pertenece a lo que se conoce como la <strong>Revolución de la Credibilidad</strong> en economía empírica, que enfatiza la importancia de identificar efectos causales en lugar de limitarse a constatar correlaciones <span class="citation" data-cites="cgl2017">(<a href="#ref-cgl2017" role="doc-biblioref">Hill et al. 2017</a>)</span>. Las técnicas que veremos en los capítulos siguientes —MCO, controles, variables instrumentales (en cursos posteriores), diferencias-en-diferencias— son herramientas para acercarnos a ese objetivo.</p>
</section>
<section id="correlación-no-implica-causalidad" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="correlación-no-implica-causalidad"><span class="header-section-number">1.4</span> Correlación no implica causalidad</h2>
<p>Una de las lecciones más importantes de la econometría es que <strong>correlación no implica causalidad</strong>. Que dos variables se muevan juntas no significa que una cause la otra. Veamos por qué.</p>
<section id="sesgo-de-selección" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="sesgo-de-selección"><span class="header-section-number">1.4.1</span> Sesgo de selección</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejemplo: ventiladores y mortalidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un hospital quiere saber si los respiradores mecánicos salvan vidas. Una comparación ingenua muestra que los pacientes que reciben respirador mueren <strong>más</strong> que los pacientes que no lo reciben. ¿Deberíamos concluir que los respiradores matan?</p>
<p>Por supuesto que no. El problema es el <strong>sesgo de selección</strong>: los pacientes más graves reciben respirador precisamente porque están en peor estado. Esos pacientes habrían tenido mayor mortalidad <strong>independientemente</strong> de si se les hubiera conectado o no a un respirador.</p>
<p>La correlación entre uso del respirador y muerte es <em>positiva</em>, pero el verdadero efecto causal es <em>negativo</em> (los respiradores salvan vidas). La comparación ingenua confunde el efecto del tratamiento con las características de quien lo recibe.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Error frecuente
</div>
</div>
<div class="callout-body-container callout-body">
<p>Comparar las medias de <span class="math inline">\(Y\)</span> entre quienes reciben un tratamiento y quienes no lo reciben <strong>no estima el efecto causal</strong> del tratamiento, salvo que la asignación al tratamiento sea independiente de los demás determinantes de <span class="math inline">\(Y\)</span>. Esta independencia raramente se da en datos observacionales.</p>
</div>
</div>
</section>
<section id="sesgo-de-variable-omitida" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="sesgo-de-variable-omitida"><span class="header-section-number">1.4.2</span> Sesgo de variable omitida</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejemplo: helados y ahogamientos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los datos muestran una fuerte correlación positiva entre las ventas de helados y los ahogamientos. ¿Deberíamos prohibir los helados para reducir las muertes por ahogamiento?</p>
<p>Obviamente no. La <strong>variable omitida</strong> es la temperatura. El calor causa <em>a la vez</em> más ventas de helados <em>y</em> más baños en piscinas y playas (y, por tanto, más ahogamientos). Sin controlar por la temperatura, la correlación entre helados y ahogamientos es completamente engañosa: es una <strong>correlación espuria</strong>.</p>
</div>
</div>
<p>Formalmente, hablamos de <strong>sesgo de variable omitida (SVO)</strong> cuando una variable <span class="math inline">\(Z\)</span> que (i) afecta a <span class="math inline">\(Y\)</span> y (ii) está correlacionada con <span class="math inline">\(X\)</span> se deja fuera del modelo. La estimación de <span class="math inline">\(\beta_1\)</span> —el efecto de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span>— absorbe parte del efecto de <span class="math inline">\(Z\)</span>. Volveremos sobre esto con detalle en el Capítulo 3.</p>
</section>
<section id="por-qué-la-aleatorización-resuelve-el-problema" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="por-qué-la-aleatorización-resuelve-el-problema"><span class="header-section-number">1.4.3</span> Por qué la aleatorización resuelve el problema</h3>
<p>Si asignamos <strong>aleatoriamente</strong> individuos a un grupo de <strong>tratamiento</strong> y otro de <strong>control</strong>, ambos grupos tendrán, en media, las mismas características —observables y no observables— <em>antes</em> del tratamiento. Cualquier diferencia en los resultados <em>después</em> del tratamiento puede entonces atribuirse al tratamiento mismo.</p>
<p>Volviendo al ejemplo de los respiradores: si pudiéramos asignar respiradores al azar (no en función de la gravedad), los grupos de tratamiento y control tendrían la misma gravedad media. La diferencia de mortalidad sería una estimación <strong>insesgada</strong> del efecto causal del respirador.</p>
<p>Por esta razón, los <strong>Ensayos Controlados Aleatorizados (ECA)</strong> son el «estándar de oro» para establecer relaciones de causalidad.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejemplo: escuelas privadas y notas en pruebas estandarizadas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un estudio observa que los estudiantes de escuelas privadas obtienen mejores notas en pruebas estandarizadas. ¿Podemos concluir que las escuelas privadas <strong>causan</strong> un mejor rendimiento?</p>
<p>No: los estudiantes de escuelas privadas suelen proceder de familias con más recursos en el hogar (libros, apoyo, expectativas, redes). Estamos de nuevo ante un sesgo de selección: la «asignación» a la escuela privada no es aleatoria.</p>
</div>
</div>
</section>
</section>
<section id="tipos-de-experimentos" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="tipos-de-experimentos"><span class="header-section-number">1.5</span> Tipos de experimentos</h2>
<p>La forma en que se generan los datos determina hasta qué punto podemos hablar de causalidad. Conviene distinguir tres grandes diseños empíricos.</p>
<section id="experimentos-aleatorizados" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="experimentos-aleatorizados"><span class="header-section-number">1.5.1</span> Experimentos aleatorizados</h3>
<p>Un <strong>experimento aleatorizado</strong> asigna a los participantes a uno o varios grupos mediante un mecanismo aleatorio (un sorteo, una tabla de números aleatorios, etc.). Uno de los grupos recibe la intervención —el <strong>tratamiento</strong>— y otro sirve como <strong>grupo de control</strong> (placebo o práctica habitual). La aleatorización garantiza, en media, la <strong>comparabilidad</strong> entre grupos y permite inferencia causal directa.</p>
<p>Sin embargo, este tipo de experimentos es <strong>poco frecuente</strong> en economía y en ciencias sociales por dos razones principales:</p>
<ul>
<li><strong>Razones éticas</strong>: no se puede asignar al azar a una persona a vivir en pobreza, a no recibir tratamiento médico o a cursar una educación de peor calidad.</li>
<li><strong>Coste y financiación</strong>: los ECA son caros y logísticamente complejos.</li>
</ul>
<p>Existen, no obstante, ejemplos célebres: el experimento RAND de seguro de salud en Estados Unidos, los programas de transferencias condicionadas tipo <em>PROGRESA/Oportunidades</em> en México, o las evaluaciones de microcréditos del J-PAL.</p>
</section>
<section id="cuasi-experimentos" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="cuasi-experimentos"><span class="header-section-number">1.5.2</span> Cuasi-experimentos</h3>
<p>Con datos <strong>cuasi-experimentales</strong>, la asignación al grupo de tratamiento y al de control <strong>no</strong> es aleatoria, sino que depende de algún criterio <strong>observable</strong> (un umbral administrativo, una regla geográfica, una fecha de corte). Cuando ese criterio es exógeno respecto del resultado de interés, el cuasi-experimento puede aproximarse a un experimento puro.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejemplo: confinamientos por umbral de contagio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Durante la pandemia de COVID-19, la Junta de Andalucía impuso confinamientos perimetrales (tratamiento) únicamente a los municipios con una tasa de contagio superior a 1.000 casos por cada 100.000 habitantes:</p>
<ul>
<li><strong>Grupo de tratamiento</strong>: municipios con tasa por encima de 1.000.</li>
<li><strong>Grupo de control</strong>: municipios con tasa por debajo de 1.000.</li>
</ul>
<p>Comparando municipios «justo por encima» y «justo por debajo» del umbral, es plausible que ambos grupos sean similares en todo lo demás y que las diferencias en, por ejemplo, movilidad o actividad económica reflejen el efecto causal del confinamiento.</p>
</div>
</div>
<p>Otros diseños cuasi-experimentales habituales son <strong>diferencias-en-diferencias</strong>, <strong>regresión discontinua</strong> y <strong>variables instrumentales</strong> (se estudian en cursos posteriores).</p>
</section>
<section id="datos-no-experimentales-observacionales" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="datos-no-experimentales-observacionales"><span class="header-section-number">1.5.3</span> Datos no experimentales (observacionales)</h3>
<p>En los datos <strong>no experimentales</strong> —típicamente encuestas— todas las variables se observan simultáneamente y la asignación a «grupos» no obedece a un diseño explícito: cada agente «se selecciona» en función de sus propias circunstancias. Son los datos más abundantes en economía aplicada.</p>
<p>Ejemplos en España:</p>
<ul>
<li>La <strong>Encuesta de Población Activa (EPA)</strong> del INE: principal fuente sobre el mercado laboral; ofrece datos trimestrales sobre empleo, paro y población activa.</li>
<li>La <strong>Encuesta Nacional de Salud (ENSE)</strong>: información sanitaria sobre miles de hogares residentes en España.</li>
<li>La <strong>Encuesta de Condiciones de Vida (ECV)</strong>.</li>
</ul>
<p>Con datos observacionales <strong>podemos estimar correlaciones</strong>, pero la interpretación causal exige supuestos adicionales (controlar por confusores observables, instrumentos válidos, diseños cuasi-experimentales, etc.). Esto explica por qué buena parte de la econometría moderna se dedica a <strong>identificar</strong> efectos causales en datos que no proceden de un experimento.</p>
</section>
</section>
<section id="tipos-de-datos-económicos" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="tipos-de-datos-económicos"><span class="header-section-number">1.6</span> Tipos de datos económicos</h2>
<p>Los datos económicos se presentan en varias formas. Una primera distinción útil es entre el <strong>nivel de agregación</strong> (datos micro frente a datos macro) y la <strong>naturaleza de las variables</strong>:</p>
<ul>
<li><strong>Cuantitativas</strong>: expresadas como números (salarios, ventas, PIB).</li>
<li><strong>Cualitativas</strong>: expresan una situación o categoría (sí/no, sector, región). En el modelo de regresión se incorporan habitualmente como <strong>variables ficticias</strong>.</li>
</ul>
<p>Una segunda distinción —la que más nos ocupará— se refiere a la <strong>estructura temporal</strong> de los datos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Datos de corte transversal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Datos recogidos sobre <strong>unidades muestrales</strong> (individuos, hogares, empresas, municipios, países) en un <strong>único período</strong>. El orden de las observaciones no contiene información: podemos reordenar las filas sin perder nada.</p>
<p><em>Ejemplo:</em> La <strong>Encuesta Nacional de Salud de España 2017</strong> recoge información sanitaria sobre 23.860 hogares en un único año.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Series temporales
</div>
</div>
<div class="callout-body-container callout-body">
<p>Datos recogidos a <strong>intervalos regulares</strong> de tiempo, donde se registra la misma magnitud económica.</p>
<p><em>Ejemplos:</em> el precio anual del trigo, la tasa de paro mensual, las cotizaciones diarias del IBEX-35.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Datos de panel (longitudinales)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Datos sobre <strong>micro-unidades individuales</strong> que se observan a lo largo de <strong>varios períodos</strong>. El rasgo clave es que observamos <em>cada</em> micro-unidad en múltiples instantes de tiempo. Si todas las unidades se observan el mismo número de períodos, el panel es <strong>balanceado</strong>.</p>
<p><em>Ejemplo:</em> 1.000 empresas seguidas durante 2010-2024, registrando ventas, empleo y exportaciones de cada empresa en cada año.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Panel agrupado (<em>pooled cross-section</em>)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Conjunto formado por la <strong>unión de varias secciones cruzadas</strong> independientes, recogidas en distintos períodos. <strong>No</strong> se siguen las mismas unidades: cada período aporta una muestra nueva. Permite analizar cambios poblacionales a lo largo del tiempo aunque no permite seguir trayectorias individuales.</p>
<p><em>Ejemplo:</em> unir varias olas de la EPA, donde cada trimestre se extrae una muestra fresca de hogares.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Error frecuente
</div>
</div>
<div class="callout-body-container callout-body">
<p>No confundir <strong>panel</strong> con <strong>panel agrupado</strong>: la diferencia clave es si las <strong>mismas</strong> unidades se siguen a lo largo del tiempo (panel) o si se extraen <strong>muestras nuevas</strong> en cada período (panel agrupado).</p>
</div>
</div>
</section>
<section id="práctica-exploración-de-datos-económicos-en-r" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="práctica-exploración-de-datos-económicos-en-r"><span class="header-section-number">1.7</span> Práctica: exploración de datos económicos en R</h2>
<p>En esta práctica usaremos el conjunto de datos <code>wage1</code> del paquete <code>wooldridge</code>, que contiene información de 526 trabajadores estadounidenses en mayo de 1976 (corte transversal). El objetivo es <strong>explorar</strong> los datos antes de cualquier modelización: calcular medias y medianas, visualizar distribuciones y obtener <strong>medias condicionales</strong> que ilustren —pero no demuestren— posibles relaciones.</p>
<p>Si es la primera vez que se usa el paquete <code>wooldridge</code>, hay que instalarlo desde la consola de R con <code>install.packages("wooldridge")</code>. La instalación se hace <strong>una sola vez</strong>; cargar el paquete con <code>library()</code> se hace en cada sesión.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="estructura-del-conjunto-de-datos" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="estructura-del-conjunto-de-datos"><span class="header-section-number">1.7.1</span> Estructura del conjunto de datos</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   526 obs. of  24 variables:
 $ wage    : num  3.1 3.24 3 6 5.3 ...
 $ educ    : int  11 12 11 8 12 16 18 12 12 17 ...
 $ exper   : int  2 22 2 44 7 9 15 5 26 22 ...
 $ tenure  : int  0 2 0 28 2 8 7 3 4 21 ...
 $ nonwhite: int  0 0 0 0 0 0 0 0 0 0 ...
 $ female  : int  1 1 0 0 0 0 0 1 1 0 ...
 $ married : int  0 1 0 1 1 1 0 0 0 1 ...
 $ numdep  : int  2 3 2 0 1 0 0 0 2 0 ...
 $ smsa    : int  1 1 0 1 0 1 1 1 1 1 ...
 $ northcen: int  0 0 0 0 0 0 0 0 0 0 ...
 $ south   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ west    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ construc: int  0 0 0 0 0 0 0 0 0 0 ...
 $ ndurman : int  0 0 0 0 0 0 0 0 0 0 ...
 $ trcommpu: int  0 0 0 0 0 0 0 0 0 0 ...
 $ trade   : int  0 0 1 0 0 0 1 0 1 0 ...
 $ services: int  0 1 0 0 0 0 0 0 0 0 ...
 $ profserv: int  0 0 0 0 0 1 0 0 0 0 ...
 $ profocc : int  0 0 0 0 0 1 1 1 1 1 ...
 $ clerocc : int  0 0 0 1 0 0 0 0 0 0 ...
 $ servocc : int  0 1 0 0 0 0 0 0 0 0 ...
 $ lwage   : num  1.13 1.18 1.1 1.79 1.67 ...
 $ expersq : int  4 484 4 1936 49 81 225 25 676 484 ...
 $ tenursq : int  0 4 0 784 4 64 49 9 16 441 ...
 - attr(*, "time.stamp")= chr "25 Jun 2011 23:03"</code></pre>
</div>
</div>
<p>Cada fila representa <strong>un trabajador</strong> observado <strong>una sola vez</strong> en mayo de 1976. No hay índice temporal ni identificadores individuales repetidos: estamos ante un <strong>corte transversal</strong>, no un panel.</p>
</section>
<section id="estadísticas-descriptivas" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="estadísticas-descriptivas"><span class="header-section-number">1.7.2</span> Estadísticas descriptivas</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"tenure"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      wage             educ           exper           tenure      
 Min.   : 0.530   Min.   : 0.00   Min.   : 1.00   Min.   : 0.000  
 1st Qu.: 3.330   1st Qu.:12.00   1st Qu.: 5.00   1st Qu.: 0.000  
 Median : 4.650   Median :12.00   Median :13.50   Median : 2.000  
 Mean   : 5.896   Mean   :12.56   Mean   :17.02   Mean   : 5.105  
 3rd Qu.: 6.880   3rd Qu.:14.00   3rd Qu.:26.00   3rd Qu.: 7.000  
 Max.   :24.980   Max.   :18.00   Max.   :51.00   Max.   :44.000  </code></pre>
</div>
</div>
<p>Las variables principales son:</p>
<ul>
<li><code>wage</code>: salario por hora en dólares de 1976.</li>
<li><code>educ</code>: años de educación.</li>
<li><code>exper</code>: años de experiencia laboral potencial.</li>
<li><code>tenure</code>: años de antigüedad en el empleo actual.</li>
</ul>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"female"</span>, <span class="st">"married"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  wage educ exper female married
1 3.10   11     2      1       0
2 3.24   12    22      1       1
3 3.00   11     2      0       0
4 6.00    8    44      0       1
5 5.30   12     7      0       1
6 8.75   16     9      0       1</code></pre>
</div>
</div>
</section>
<section id="distribuciones" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="distribuciones"><span class="header-section-number">1.7.3</span> Distribuciones</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>wage,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribución del salario por hora"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Salario (USD/h)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-conceptos-iniciales_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribución del salario por hora (USD).</figcaption>
</figure>
</div>
</div>
</div>
<p>La distribución del salario es claramente <strong>asimétrica a la derecha</strong>: la media (aproximadamente 5,90 USD/h) es mayor que la mediana (4,65 USD/h), lo que indica una cola larga de salarios altos. Es un patrón habitual en datos de renta y salarios.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">18</span>, <span class="at">col =</span> <span class="st">"lightgreen"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Años de educación"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-conceptos-iniciales_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribución de los años de educación.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="diagrama-de-dispersión-salario-frente-a-educación" class="level3" data-number="1.7.4">
<h3 data-number="1.7.4" class="anchored" data-anchor-id="diagrama-de-dispersión-salario-frente-a-educación"><span class="header-section-number">1.7.4</span> Diagrama de dispersión: salario frente a educación</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>wage,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.3</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Salario por hora (USD)"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Salario vs. educación"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(wage <span class="sc">~</span> educ, <span class="at">data =</span> wage1), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-conceptos-iniciales_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Salario por hora frente a años de educación. La línea roja es el ajuste por MCO.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4059033</code></pre>
</div>
</div>
<p>La correlación entre salario y educación es aproximadamente <strong>0,41</strong>: positiva, como esperaríamos. Pero conviene ser cauto en la interpretación:</p>
<ol type="1">
<li>La nube muestra <strong>heterocedasticidad</strong>: la varianza del salario es mucho mayor para niveles altos de educación que para niveles bajos (volveremos sobre esto en el Capítulo 7).</li>
<li>La correlación <strong>no es</strong> el efecto causal de la educación sobre el salario. Las personas con más años de estudios difieren en habilidad innata, motivación, origen familiar y muchas otras dimensiones que también están en <span class="math inline">\(u\)</span>.</li>
</ol>
</section>
<section id="medias-condicionales" class="level3" data-number="1.7.5">
<h3 data-number="1.7.5" class="anchored" data-anchor-id="medias-condicionales"><span class="header-section-number">1.7.5</span> Medias condicionales</h3>
<p>Una forma rápida de detectar asociaciones brutas es calcular la <strong>media de <span class="math inline">\(Y\)</span> por grupos</strong> definidos por una variable categórica. En R lo hacemos con <code>tapply()</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por género (female = 1 si mujer)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>female, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
7.099489 4.587659 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por estado civil</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>married, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
4.843884 6.573469 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por intervalos de educación</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>wage1<span class="sc">$</span>educ_grupo <span class="ot">&lt;-</span> <span class="fu">cut</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">18</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Hasta 8"</span>, <span class="st">"9-12"</span>, <span class="st">"13-16"</span>, <span class="st">"17+"</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ_grupo, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Hasta 8      9-12     13-16       17+ 
 4.461000  4.947701  6.785746 10.936129 </code></pre>
</div>
</div>
<p>Estos números son <strong>medias condicionales</strong>, no efectos causales. La brecha salarial bruta entre hombres y mujeres (aproximadamente 7,10 vs.&nbsp;4,59 USD/h) refleja diferencias en ocupación, experiencia, sector, horas, decisiones de fecundidad, posible discriminación, etc. Para interpretarlas como efectos <em>ceteris paribus</em> necesitaremos una <strong>regresión múltiple</strong> que mantenga fijos los confusores observables (Capítulo 3).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Pista: ¿qué pasa si estimamos un MCO simple aquí?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Es perfectamente posible escribir <code>summary(lm(wage ~ educ, data = wage1))</code> ahora mismo. Pero la interpretación del coeficiente como «retorno causal de un año de educación» exige supuestos fuertes (no SVO, no sesgo de selección). En el Capítulo 2 estimaremos este modelo con cuidado; en el Capítulo 3 introduciremos controles.</p>
</div>
</div>
</div>
</section>
</section>
<section id="auto-evaluación" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="auto-evaluación">Auto-evaluación</h2>
<p>Ocho preguntas breves de opción múltiple. Intenta responder cada una antes de desplegar la solución.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q1. ¿Qué es un modelo econométrico?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Un modelo econométrico se diferencia de un modelo económico puramente teórico en que:</p>
<ul>
<li>A. Supone que la relación entre variables es exacta y determinista.</li>
<li>B. Añade un término de error estocástico y una forma funcional, de modo que los parámetros desconocidos puedan estimarse a partir de datos.</li>
<li>C. No necesita una muestra de datos porque los parámetros se derivan de la teoría.</li>
<li>D. Solo se utiliza en problemas macroeconómicos, no en microeconómicos.</li>
</ul>
<p><strong>Respuesta: B.</strong> Un modelo econométrico combina una forma funcional con una perturbación aleatoria <span class="math inline">\(u\)</span>, lo que permite estimar los parámetros desconocidos a partir de los datos observados.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q2. El papel del término de error
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>En el modelo de regresión poblacional <span class="math inline">\(y = \beta_0 + \beta_1 x + u\)</span>, el término de error <span class="math inline">\(u\)</span>:</p>
<ul>
<li>A. Es la diferencia entre <span class="math inline">\(y_i\)</span> y el valor ajustado por MCO <span class="math inline">\(\hat{y}_i\)</span> en nuestra muestra.</li>
<li>B. Es siempre igual a cero en la población.</li>
<li>C. Recoge todos los factores —distintos de <span class="math inline">\(x\)</span>— que influyen sobre <span class="math inline">\(y\)</span>.</li>
<li>D. Es observable tan pronto como disponemos de datos de <span class="math inline">\(y\)</span> y <span class="math inline">\(x\)</span>.</li>
</ul>
<p><strong>Respuesta: C.</strong> <span class="math inline">\(u\)</span> es una magnitud <em>poblacional</em> y <em>no observable</em> que agrupa todos los determinantes omitidos de <span class="math inline">\(y\)</span>. El residuo <span class="math inline">\(\hat{u}_i\)</span> es su análogo muestral, calculado solo tras la estimación.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q3. ¿Corte transversal o no?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Un conjunto de datos con información sobre 526 trabajadores entrevistados en mayo de 1976 (una observación por trabajador, todos medidos en el mismo instante) es:</p>
<ul>
<li>A. Datos de corte transversal.</li>
<li>B. Datos de series temporales.</li>
<li>C. Datos de panel (longitudinales).</li>
<li>D. Panel agrupado.</li>
</ul>
<p><strong>Respuesta: A.</strong> Muchas unidades, un único período, sin observaciones repetidas de la misma unidad: la definición estándar de corte transversal.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q4. Series temporales
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Las tasas anuales de paro en España de 1980 a 2024 son un ejemplo de:</p>
<ul>
<li>A. Datos de corte transversal.</li>
<li>B. Datos de series temporales.</li>
<li>C. Datos de panel.</li>
<li>D. Datos experimentales.</li>
</ul>
<p><strong>Respuesta: B.</strong> Una única magnitud (la tasa de paro) registrada a una frecuencia regular en el tiempo.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q5. Panel frente a panel agrupado
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Una base de datos sigue a 1.000 empresas durante los años 2010-2024, registrando las ventas, el empleo y las exportaciones de cada empresa en cada año. Esto es:</p>
<ul>
<li>A. Datos de corte transversal, ya que cada fila es un par empresa-año.</li>
<li>B. Panel agrupado, ya que se muestrean unidades distintas en cada período.</li>
<li>C. Datos de series temporales, ya que tiene una dimensión temporal.</li>
<li>D. Datos de panel (longitudinales): las mismas unidades observadas repetidamente a lo largo del tiempo.</li>
</ul>
<p><strong>Respuesta: D.</strong> Las mismas empresas se siguen a lo largo de varios períodos, que es exactamente la estructura de panel.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q6. ¿Qué nos dice la correlación?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Una correlación positiva alta entre dos variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> implica que:</p>
<ul>
<li>A. <span class="math inline">\(X\)</span> causa <span class="math inline">\(Y\)</span>.</li>
<li>B. <span class="math inline">\(Y\)</span> causa <span class="math inline">\(X\)</span>.</li>
<li>C. Existe una relación lineal determinista entre ambas.</li>
<li>D. Tienden a moverse juntas, pero esta asociación puede deberse a una tercera variable, a causalidad inversa o a sesgo de selección.</li>
</ul>
<p><strong>Respuesta: D.</strong> La correlación no dice nada sobre la dirección causal ni sobre la presencia de confusores. El ejemplo de los helados y los ahogamientos del §1.4.2 es la advertencia canónica.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q7. Sesgo de selección
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El sesgo de selección aparece cuando:</p>
<ul>
<li>A. Las unidades que se «seleccionan» en el grupo de tratamiento difieren sistemáticamente de las que no, incluso antes del tratamiento.</li>
<li>B. El investigador elige los regresores en función de los estadísticos <span class="math inline">\(t\)</span>.</li>
<li>C. El tamaño muestral es demasiado pequeño para detectar un efecto verdadero.</li>
<li>D. La variable dependiente se mide con error.</li>
</ul>
<p><strong>Respuesta: A.</strong> El sesgo de selección es una propiedad de la <em>asignación</em> del tratamiento, no de la estimación ni de la medición. El ejemplo de los respiradores del §1.4.1 es el prototipo.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q8. La aleatorización como remedio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>¿En cuál de los siguientes diseños la aleatorización elimina <em>por construcción</em> el sesgo de selección?</p>
<ul>
<li>A. Comparar individuos empleados frente a desempleados utilizando datos de encuesta de corte transversal.</li>
<li>B. Un Ensayo Controlado Aleatorizado (ECA) en el que el tratamiento se asigna por sorteo.</li>
<li>C. Comparar estudiantes que eligieron matricularse en una escuela privada frente a una pública.</li>
<li>D. Comparar países que adoptaron el euro frente a países que no lo hicieron.</li>
</ul>
<p><strong>Respuesta: B.</strong> Solo la asignación aleatoria garantiza que, <em>en media</em>, las unidades tratadas y no tratadas tengan las mismas características previas al tratamiento.</p>
</div>
</div>
</div>
</section>
<section id="ejercicios" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ejercicios">Ejercicios</h2>
<p><strong>Ejercicio 1.1 ★ — Clasificación de conjuntos de datos.</strong> Clasifique cada uno de los siguientes conjuntos de datos como corte transversal, serie temporal, panel o panel agrupado.</p>
<ol type="a">
<li>IPC mensual español de 1980 a 2024.</li>
<li><code>wage1</code>: 526 trabajadores entrevistados en mayo de 1976, una fila por trabajador.</li>
<li>La EPA española: cada trimestre se extrae una muestra independiente nueva de hogares (no se vuelve a entrevistar a ningún hogar); después se apilan varios trimestres.</li>
<li>Un conjunto de datos que sigue a los mismos 800 estudiantes desde los 6 hasta los 18 años, registrando sus puntuaciones cada año.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Mostrar solución
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Serie temporal. (b) Corte transversal. (c) Panel agrupado — unidades nuevas en cada período. (d) Panel: las <em>mismas</em> unidades se siguen a lo largo de varios períodos.</li>
</ol>
</div>
</div>
</div>
<p><strong>Ejercicio 1.2 ★ — Detectar sesgo de selección.</strong> Para cada escenario, indique si el sesgo de selección es un problema probable e identifique qué característica lo origina.</p>
<ol type="a">
<li>Un hospital compara la mortalidad de los pacientes que recibieron respirador con la de los pacientes que no lo recibieron.</li>
<li>Un economista compara los salarios de los trabajadores que completaron un programa de formación laboral con los salarios de los trabajadores que no se inscribieron.</li>
<li>Unos investigadores comparan los países que adoptaron el euro en 1999 con los países que no lo hicieron.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Mostrar solución
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Sí — la gravedad de la enfermedad determina tanto la asignación del respirador como la mortalidad. (b) Sí — la autoselección hacia la formación viene impulsada por la motivación, los ingresos previos y las perspectivas en el mercado laboral, todo lo cual también afecta al salario. (c) Sí — los países que se unieron al euro fueron elegidos en función de fundamentos macroeconómicos (los criterios de Maastricht), por lo que no son una muestra aleatoria de países europeos.</li>
</ol>
</div>
</div>
</div>
<p><strong>Ejercicio 1.3 ★★ — Signo del sesgo de variable omitida.</strong> Suponga que regresa el salario por hora sobre los años de educación en una muestra de adultos actualmente empleados, <em>sin</em> controlar por la habilidad innata. Suponga que (i) los trabajadores más hábiles ganan más, manteniendo fija la educación, y (ii) los trabajadores más hábiles tienden a adquirir más educación. ¿Estará el coeficiente de <code>educ</code> sesgado al alza (demasiado positivo) o a la baja (demasiado negativo)? Explique en una frase.</p>
<p><em>La solución completa se ofrece en la Edición del Profesor.</em></p>
<p><strong>Ejercicio 1.4 ★★ — Diseño de un experimento aleatorizado.</strong> Desea saber si un curso gratuito de preparación para la universidad (el tratamiento) eleva causalmente la probabilidad de que los estudiantes de secundaria de familias con renta baja se matriculen en la universidad. Esboce el diseño de un experimento aleatorizado que permita identificar este efecto causal. Sea explícito en cuanto a: la población, la regla de asignación, los grupos de tratamiento y control, la variable de resultado y el horizonte temporal. Discuta brevemente una objeción ética que su diseño deberá abordar.</p>
<p><em>La solución completa se ofrece en la Edición del Profesor.</em></p>
<p><strong>Ejercicio 1.5 ★★ — Un modelo ingenuo con variable omitida.</strong> El salario de un trabajador se genera mediante</p>
<p><span class="math display">\[
w = 5 + 2 \cdot \mathit{edu} + u, \qquad \mathbb{E}[u] = 0,\ \operatorname{Var}(u) = 1,
\]</span></p>
<p>donde <span class="math inline">\(\mathit{edu}\in\{0,1,2,3\}\)</span> son los años de educación postobligatoria. Suponga que la habilidad (recogida en <span class="math inline">\(u\)</span>) está correlacionada con la educación: <span class="math inline">\(\mathbb{E}[u\mid \mathit{edu}] = 0{,}5\cdot \mathit{edu}\)</span>.</p>
<ol type="a">
<li>Calcule <span class="math inline">\(\mathbb{E}[w\mid \mathit{edu}]\)</span>.</li>
<li>Si ingenuamente suponemos <span class="math inline">\(\mathbb{E}[u\mid \mathit{edu}] = 0\)</span> y leemos la pendiente, ¿qué obtenemos? ¿En cuánto nos <em>desviamos</em> del verdadero efecto marginal de un año adicional de educación?</li>
</ol>
<p><em>La solución completa se ofrece en la Edición del Profesor.</em></p>
<p><strong>Ejercicio 1.6 ★★★ — Chocolate y premios Nobel.</strong> Se ha documentado <span class="citation" data-cites="cgl2017">(<a href="#ref-cgl2017" role="doc-biblioref">Hill et al. 2017</a>)</span> que los países con mayor consumo de chocolate per cápita también ganan más premios Nobel per cápita. ¿Es esto evidencia de que el consumo de chocolate <em>causa</em> premios Nobel? Identifique (i) al menos una variable omitida plausible, (ii) al menos un canal causal alternativo (causalidad inversa, selección de los países que se miden, etc.) y (iii) describa un diseño de investigación <em>hipotético</em> — experimental o cuasi-experimental — que le permitiera conocer el efecto causal del chocolate sobre la obtención de premios. Sea sincero respecto a por qué es poco probable que este diseño sea factible.</p>
<p><em>La solución completa se ofrece en la Edición del Profesor.</em></p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-cgl2017" class="csl-entry" role="listitem">
Hill, R. Carter, William E. Griffiths, and Guay C. Lim. 2017. <em>Principles of Econometrics</em>. 5th ed. Wiley.
</div>
<div id="ref-wooldridge2020" class="csl-entry" role="listitem">
Wooldridge, Jeffrey M. 2020. <em>Introductory Econometrics: A Modern Approach</em>. 7th ed. Cengage Learning.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link" aria-label="Prefacio">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Prefacio</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/02-regresion-simple.html" class="pagination-link" aria-label="El Modelo de Regresión Lineal Simple">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El Modelo de Regresión Lineal Simple</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Conceptos Iniciales"</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivos de aprendizaje {.unnumbered}</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Definir** qué es la econometría y distinguirla de un modelo puramente teórico.</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Identificar** las dos componentes de un modelo econométrico —parte sistemática y término de error— y reconocer los parámetros desconocidos $\beta_0, \beta_1, \ldots$</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Explicar** por qué correlación no implica causalidad y **diagnosticar** sesgo de selección y sesgo de variable omitida en ejemplos aplicados.</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Distinguir** los tres grandes diseños empíricos en economía: experimentos aleatorizados, cuasi-experimentos y datos observacionales.</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Clasificar** un conjunto de datos económicos como de corte transversal, de series temporales, de panel o panel agrupado.</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Explorar** un conjunto de datos en R con `str()`, `summary()`, `head()`, `hist()`, `plot()` y `tapply()`, y **calcular** medias condicionales para detectar asociaciones brutas.</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pregunta motivadora {.unnumbered}</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *¿Asistir a la universidad **causa** mayores salarios, o las personas que de todos modos habrían ganado más tienden a ir a la universidad?*</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>A lo largo del curso veremos que responder a esta pregunta —y a muchas otras del mismo tipo— exige algo más que una simple correlación entre nivel educativo y salario. Hace falta un **modelo**, una **muestra** y, sobre todo, un **diseño** que nos permita atribuir las diferencias observadas a la causa que nos interesa.</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="fu">## ¿Qué es la Econometría?</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="in">`\lettrine[lines=3]{L}{a}`</span>{=latex} **econometría** es la aplicación de métodos estadísticos a datos económicos con el fin de dar contenido empírico a las relaciones económicas. Su objetivo principal es la **estimación** y **contraste** de relaciones entre variables económicas. Algunos ejemplos típicos:</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Educación $\Rightarrow$ Salario</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Asistencia a clase $\Rightarrow$ Nota final</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Tasas de matrícula $\Rightarrow$ Inscripción</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Renta $\Rightarrow$ Felicidad</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Gasto público en seguridad $\Rightarrow$ Criminalidad</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Publicidad $\Rightarrow$ Ventas</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>En general nos referimos a estas variables como $X \Rightarrow Y$, donde $X$ es la **variable independiente** (también llamada regresora o explicativa) e $Y$ es la **variable dependiente** (también respuesta o resultado). Frente a cualquier relación de este tipo surgen dos preguntas fundamentales:</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>¿**Existe** un efecto de $X$ sobre $Y$?</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Cuál es la **magnitud** del efecto?</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Decisores y preguntas de «¿cuánto?»</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>Cada día, quienes toman decisiones se enfrentan a preguntas cuantitativas:</span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un ayuntamiento se plantea cuánto se reducirá el crimen violento si se destina un millón de euros adicional a poner más policías en la calle.</span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El propietario de una pizzería local debe decidir cuánto invertir en publicidad digital y, por tanto, necesita estimar la relación entre publicidad y ventas.</span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Una universidad privada en Andalucía necesita estimar en cuánto disminuirá la matrícula si sube la tasa anual 300 euros.</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>La econometría es la caja de herramientas para responder este tipo de preguntas con datos <span class="co">[</span><span class="ot">@wooldridge2020</span><span class="co">]</span>.</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## El modelo econométrico</span></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>El modelo econométrico consta de **dos componentes**:</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**La parte sistemática**: el comportamiento medio de muchos individuos, empresas u observaciones.</span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**El error aleatorio** $u$: recoge todos los factores que afectan a $Y$ y que se han omitido en la especificación.</span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplo: determinación del salario</span></span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a>Algunos factores asociados al salario por hora de un individuo son la edad, el género, la experiencia y la educación:</span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a>\text{Salario} = f(\text{Edad},\ \text{Género},\ \text{Experiencia},\ \text{Educación}) + u</span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a>Una especificación **lineal** sería:</span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>\text{Salario} = \beta_0 + \beta_1\,\text{Edad} + \beta_2\,\text{Género} + \beta_3\,\text{Experiencia} + \beta_4\,\text{Educación} + u</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-67"><a href="#cb19-67" aria-hidden="true" tabindex="-1"></a>Los coeficientes $\beta_0, \beta_1, \ldots, \beta_4$ son **parámetros desconocidos** que queremos estimar a partir de una muestra de datos y de una técnica econométrica (por ejemplo, Mínimos Cuadrados Ordinarios; véase el Capítulo 2).</span>
<span id="cb19-68"><a href="#cb19-68" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-69"><a href="#cb19-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-70"><a href="#cb19-70" aria-hidden="true" tabindex="-1"></a>Dos observaciones importantes:</span>
<span id="cb19-71"><a href="#cb19-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-72"><a href="#cb19-72" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La **forma funcional** (lineal, log-lineal, cuadrática, …) representa una hipótesis sobre la relación entre variables. En cada problema, uno de los retos consiste en elegir una forma funcional compatible con la teoría económica y con los datos.</span>
<span id="cb19-73"><a href="#cb19-73" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El error $u$ **no es observable**. Cuando estimamos el modelo en una muestra, obtenemos los **residuos** $\hat{u}_i = y_i - \hat{y}_i$, que son la versión muestral —y observable— del error poblacional.</span>
<span id="cb19-74"><a href="#cb19-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-75"><a href="#cb19-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## Usos de la econometría</span></span>
<span id="cb19-76"><a href="#cb19-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-77"><a href="#cb19-77" aria-hidden="true" tabindex="-1"></a>El modelo econométrico cumple tres grandes funciones, que conviene distinguir desde el principio:</span>
<span id="cb19-78"><a href="#cb19-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-79"><a href="#cb19-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Contrastar teorías e hipótesis económicas**. Por ejemplo: ¿reduce el empleo un aumento del salario mínimo?</span>
<span id="cb19-80"><a href="#cb19-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Predecir variables económicas**. Por ejemplo: pronosticar el crecimiento del PIB o el precio de las acciones de una empresa.</span>
<span id="cb19-81"><a href="#cb19-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Estimar relaciones causales**. Por ejemplo: ¿un año adicional de educación **causa** un salario más alto, ceteris paribus?</span>
<span id="cb19-82"><a href="#cb19-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-83"><a href="#cb19-83" aria-hidden="true" tabindex="-1"></a>El tercer punto pertenece a lo que se conoce como la **Revolución de la Credibilidad** en economía empírica, que enfatiza la importancia de identificar efectos causales en lugar de limitarse a constatar correlaciones <span class="co">[</span><span class="ot">@cgl2017</span><span class="co">]</span>. Las técnicas que veremos en los capítulos siguientes —MCO, controles, variables instrumentales (en cursos posteriores), diferencias-en-diferencias— son herramientas para acercarnos a ese objetivo.</span>
<span id="cb19-84"><a href="#cb19-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-85"><a href="#cb19-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## Correlación no implica causalidad</span></span>
<span id="cb19-86"><a href="#cb19-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-87"><a href="#cb19-87" aria-hidden="true" tabindex="-1"></a>Una de las lecciones más importantes de la econometría es que **correlación no implica causalidad**. Que dos variables se muevan juntas no significa que una cause la otra. Veamos por qué.</span>
<span id="cb19-88"><a href="#cb19-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-89"><a href="#cb19-89" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sesgo de selección</span></span>
<span id="cb19-90"><a href="#cb19-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-91"><a href="#cb19-91" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-92"><a href="#cb19-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplo: ventiladores y mortalidad</span></span>
<span id="cb19-93"><a href="#cb19-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-94"><a href="#cb19-94" aria-hidden="true" tabindex="-1"></a>Un hospital quiere saber si los respiradores mecánicos salvan vidas. Una comparación ingenua muestra que los pacientes que reciben respirador mueren **más** que los pacientes que no lo reciben. ¿Deberíamos concluir que los respiradores matan?</span>
<span id="cb19-95"><a href="#cb19-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-96"><a href="#cb19-96" aria-hidden="true" tabindex="-1"></a>Por supuesto que no. El problema es el **sesgo de selección**: los pacientes más graves reciben respirador precisamente porque están en peor estado. Esos pacientes habrían tenido mayor mortalidad **independientemente** de si se les hubiera conectado o no a un respirador.</span>
<span id="cb19-97"><a href="#cb19-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-98"><a href="#cb19-98" aria-hidden="true" tabindex="-1"></a>La correlación entre uso del respirador y muerte es *positiva*, pero el verdadero efecto causal es *negativo* (los respiradores salvan vidas). La comparación ingenua confunde el efecto del tratamiento con las características de quien lo recibe.</span>
<span id="cb19-99"><a href="#cb19-99" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-100"><a href="#cb19-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-101"><a href="#cb19-101" aria-hidden="true" tabindex="-1"></a>:::{.callout-warning}</span>
<span id="cb19-102"><a href="#cb19-102" aria-hidden="true" tabindex="-1"></a><span class="fu">## Error frecuente</span></span>
<span id="cb19-103"><a href="#cb19-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-104"><a href="#cb19-104" aria-hidden="true" tabindex="-1"></a>Comparar las medias de $Y$ entre quienes reciben un tratamiento y quienes no lo reciben **no estima el efecto causal** del tratamiento, salvo que la asignación al tratamiento sea independiente de los demás determinantes de $Y$. Esta independencia raramente se da en datos observacionales.</span>
<span id="cb19-105"><a href="#cb19-105" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-106"><a href="#cb19-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-107"><a href="#cb19-107" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sesgo de variable omitida</span></span>
<span id="cb19-108"><a href="#cb19-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-109"><a href="#cb19-109" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-110"><a href="#cb19-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplo: helados y ahogamientos</span></span>
<span id="cb19-111"><a href="#cb19-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-112"><a href="#cb19-112" aria-hidden="true" tabindex="-1"></a>Los datos muestran una fuerte correlación positiva entre las ventas de helados y los ahogamientos. ¿Deberíamos prohibir los helados para reducir las muertes por ahogamiento?</span>
<span id="cb19-113"><a href="#cb19-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-114"><a href="#cb19-114" aria-hidden="true" tabindex="-1"></a>Obviamente no. La **variable omitida** es la temperatura. El calor causa *a la vez* más ventas de helados *y* más baños en piscinas y playas (y, por tanto, más ahogamientos). Sin controlar por la temperatura, la correlación entre helados y ahogamientos es completamente engañosa: es una **correlación espuria**.</span>
<span id="cb19-115"><a href="#cb19-115" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-116"><a href="#cb19-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-117"><a href="#cb19-117" aria-hidden="true" tabindex="-1"></a>Formalmente, hablamos de **sesgo de variable omitida (SVO)** cuando una variable $Z$ que (i) afecta a $Y$ y (ii) está correlacionada con $X$ se deja fuera del modelo. La estimación de $\beta_1$ —el efecto de $X$ sobre $Y$— absorbe parte del efecto de $Z$. Volveremos sobre esto con detalle en el Capítulo 3.</span>
<span id="cb19-118"><a href="#cb19-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-119"><a href="#cb19-119" aria-hidden="true" tabindex="-1"></a><span class="fu">### Por qué la aleatorización resuelve el problema</span></span>
<span id="cb19-120"><a href="#cb19-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-121"><a href="#cb19-121" aria-hidden="true" tabindex="-1"></a>Si asignamos **aleatoriamente** individuos a un grupo de **tratamiento** y otro de **control**, ambos grupos tendrán, en media, las mismas características —observables y no observables— *antes* del tratamiento. Cualquier diferencia en los resultados *después* del tratamiento puede entonces atribuirse al tratamiento mismo.</span>
<span id="cb19-122"><a href="#cb19-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-123"><a href="#cb19-123" aria-hidden="true" tabindex="-1"></a>Volviendo al ejemplo de los respiradores: si pudiéramos asignar respiradores al azar (no en función de la gravedad), los grupos de tratamiento y control tendrían la misma gravedad media. La diferencia de mortalidad sería una estimación **insesgada** del efecto causal del respirador.</span>
<span id="cb19-124"><a href="#cb19-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-125"><a href="#cb19-125" aria-hidden="true" tabindex="-1"></a>Por esta razón, los **Ensayos Controlados Aleatorizados (ECA)** son el «estándar de oro» para establecer relaciones de causalidad.</span>
<span id="cb19-126"><a href="#cb19-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-127"><a href="#cb19-127" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-128"><a href="#cb19-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplo: escuelas privadas y notas en pruebas estandarizadas</span></span>
<span id="cb19-129"><a href="#cb19-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-130"><a href="#cb19-130" aria-hidden="true" tabindex="-1"></a>Un estudio observa que los estudiantes de escuelas privadas obtienen mejores notas en pruebas estandarizadas. ¿Podemos concluir que las escuelas privadas **causan** un mejor rendimiento?</span>
<span id="cb19-131"><a href="#cb19-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-132"><a href="#cb19-132" aria-hidden="true" tabindex="-1"></a>No: los estudiantes de escuelas privadas suelen proceder de familias con más recursos en el hogar (libros, apoyo, expectativas, redes). Estamos de nuevo ante un sesgo de selección: la «asignación» a la escuela privada no es aleatoria.</span>
<span id="cb19-133"><a href="#cb19-133" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-134"><a href="#cb19-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-135"><a href="#cb19-135" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tipos de experimentos</span></span>
<span id="cb19-136"><a href="#cb19-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-137"><a href="#cb19-137" aria-hidden="true" tabindex="-1"></a>La forma en que se generan los datos determina hasta qué punto podemos hablar de causalidad. Conviene distinguir tres grandes diseños empíricos.</span>
<span id="cb19-138"><a href="#cb19-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-139"><a href="#cb19-139" aria-hidden="true" tabindex="-1"></a><span class="fu">### Experimentos aleatorizados</span></span>
<span id="cb19-140"><a href="#cb19-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-141"><a href="#cb19-141" aria-hidden="true" tabindex="-1"></a>Un **experimento aleatorizado** asigna a los participantes a uno o varios grupos mediante un mecanismo aleatorio (un sorteo, una tabla de números aleatorios, etc.). Uno de los grupos recibe la intervención —el **tratamiento**— y otro sirve como **grupo de control** (placebo o práctica habitual). La aleatorización garantiza, en media, la **comparabilidad** entre grupos y permite inferencia causal directa.</span>
<span id="cb19-142"><a href="#cb19-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-143"><a href="#cb19-143" aria-hidden="true" tabindex="-1"></a>Sin embargo, este tipo de experimentos es **poco frecuente** en economía y en ciencias sociales por dos razones principales:</span>
<span id="cb19-144"><a href="#cb19-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-145"><a href="#cb19-145" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Razones éticas**: no se puede asignar al azar a una persona a vivir en pobreza, a no recibir tratamiento médico o a cursar una educación de peor calidad.</span>
<span id="cb19-146"><a href="#cb19-146" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Coste y financiación**: los ECA son caros y logísticamente complejos.</span>
<span id="cb19-147"><a href="#cb19-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-148"><a href="#cb19-148" aria-hidden="true" tabindex="-1"></a>Existen, no obstante, ejemplos célebres: el experimento RAND de seguro de salud en Estados Unidos, los programas de transferencias condicionadas tipo *PROGRESA/Oportunidades* en México, o las evaluaciones de microcréditos del J-PAL.</span>
<span id="cb19-149"><a href="#cb19-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-150"><a href="#cb19-150" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cuasi-experimentos</span></span>
<span id="cb19-151"><a href="#cb19-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-152"><a href="#cb19-152" aria-hidden="true" tabindex="-1"></a>Con datos **cuasi-experimentales**, la asignación al grupo de tratamiento y al de control **no** es aleatoria, sino que depende de algún criterio **observable** (un umbral administrativo, una regla geográfica, una fecha de corte). Cuando ese criterio es exógeno respecto del resultado de interés, el cuasi-experimento puede aproximarse a un experimento puro.</span>
<span id="cb19-153"><a href="#cb19-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-154"><a href="#cb19-154" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-155"><a href="#cb19-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplo: confinamientos por umbral de contagio</span></span>
<span id="cb19-156"><a href="#cb19-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-157"><a href="#cb19-157" aria-hidden="true" tabindex="-1"></a>Durante la pandemia de COVID-19, la Junta de Andalucía impuso confinamientos perimetrales (tratamiento) únicamente a los municipios con una tasa de contagio superior a 1.000 casos por cada 100.000 habitantes:</span>
<span id="cb19-158"><a href="#cb19-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-159"><a href="#cb19-159" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Grupo de tratamiento**: municipios con tasa por encima de 1.000.</span>
<span id="cb19-160"><a href="#cb19-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Grupo de control**: municipios con tasa por debajo de 1.000.</span>
<span id="cb19-161"><a href="#cb19-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-162"><a href="#cb19-162" aria-hidden="true" tabindex="-1"></a>Comparando municipios «justo por encima» y «justo por debajo» del umbral, es plausible que ambos grupos sean similares en todo lo demás y que las diferencias en, por ejemplo, movilidad o actividad económica reflejen el efecto causal del confinamiento.</span>
<span id="cb19-163"><a href="#cb19-163" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-164"><a href="#cb19-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-165"><a href="#cb19-165" aria-hidden="true" tabindex="-1"></a>Otros diseños cuasi-experimentales habituales son **diferencias-en-diferencias**, **regresión discontinua** y **variables instrumentales** (se estudian en cursos posteriores).</span>
<span id="cb19-166"><a href="#cb19-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-167"><a href="#cb19-167" aria-hidden="true" tabindex="-1"></a><span class="fu">### Datos no experimentales (observacionales)</span></span>
<span id="cb19-168"><a href="#cb19-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-169"><a href="#cb19-169" aria-hidden="true" tabindex="-1"></a>En los datos **no experimentales** —típicamente encuestas— todas las variables se observan simultáneamente y la asignación a «grupos» no obedece a un diseño explícito: cada agente «se selecciona» en función de sus propias circunstancias. Son los datos más abundantes en economía aplicada.</span>
<span id="cb19-170"><a href="#cb19-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-171"><a href="#cb19-171" aria-hidden="true" tabindex="-1"></a>Ejemplos en España:</span>
<span id="cb19-172"><a href="#cb19-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-173"><a href="#cb19-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La **Encuesta de Población Activa (EPA)** del INE: principal fuente sobre el mercado laboral; ofrece datos trimestrales sobre empleo, paro y población activa.</span>
<span id="cb19-174"><a href="#cb19-174" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La **Encuesta Nacional de Salud (ENSE)**: información sanitaria sobre miles de hogares residentes en España.</span>
<span id="cb19-175"><a href="#cb19-175" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La **Encuesta de Condiciones de Vida (ECV)**.</span>
<span id="cb19-176"><a href="#cb19-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-177"><a href="#cb19-177" aria-hidden="true" tabindex="-1"></a>Con datos observacionales **podemos estimar correlaciones**, pero la interpretación causal exige supuestos adicionales (controlar por confusores observables, instrumentos válidos, diseños cuasi-experimentales, etc.). Esto explica por qué buena parte de la econometría moderna se dedica a **identificar** efectos causales en datos que no proceden de un experimento.</span>
<span id="cb19-178"><a href="#cb19-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-179"><a href="#cb19-179" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tipos de datos económicos</span></span>
<span id="cb19-180"><a href="#cb19-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-181"><a href="#cb19-181" aria-hidden="true" tabindex="-1"></a>Los datos económicos se presentan en varias formas. Una primera distinción útil es entre el **nivel de agregación** (datos micro frente a datos macro) y la **naturaleza de las variables**:</span>
<span id="cb19-182"><a href="#cb19-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-183"><a href="#cb19-183" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cuantitativas**: expresadas como números (salarios, ventas, PIB).</span>
<span id="cb19-184"><a href="#cb19-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cualitativas**: expresan una situación o categoría (sí/no, sector, región). En el modelo de regresión se incorporan habitualmente como **variables ficticias**.</span>
<span id="cb19-185"><a href="#cb19-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-186"><a href="#cb19-186" aria-hidden="true" tabindex="-1"></a>Una segunda distinción —la que más nos ocupará— se refiere a la **estructura temporal** de los datos.</span>
<span id="cb19-187"><a href="#cb19-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-188"><a href="#cb19-188" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-189"><a href="#cb19-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Datos de corte transversal</span></span>
<span id="cb19-190"><a href="#cb19-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-191"><a href="#cb19-191" aria-hidden="true" tabindex="-1"></a>Datos recogidos sobre **unidades muestrales** (individuos, hogares, empresas, municipios, países) en un **único período**. El orden de las observaciones no contiene información: podemos reordenar las filas sin perder nada.</span>
<span id="cb19-192"><a href="#cb19-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-193"><a href="#cb19-193" aria-hidden="true" tabindex="-1"></a>*Ejemplo:* La **Encuesta Nacional de Salud de España 2017** recoge información sanitaria sobre 23.860 hogares en un único año.</span>
<span id="cb19-194"><a href="#cb19-194" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-195"><a href="#cb19-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-196"><a href="#cb19-196" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-197"><a href="#cb19-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## Series temporales</span></span>
<span id="cb19-198"><a href="#cb19-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-199"><a href="#cb19-199" aria-hidden="true" tabindex="-1"></a>Datos recogidos a **intervalos regulares** de tiempo, donde se registra la misma magnitud económica.</span>
<span id="cb19-200"><a href="#cb19-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-201"><a href="#cb19-201" aria-hidden="true" tabindex="-1"></a>*Ejemplos:* el precio anual del trigo, la tasa de paro mensual, las cotizaciones diarias del IBEX-35.</span>
<span id="cb19-202"><a href="#cb19-202" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-203"><a href="#cb19-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-204"><a href="#cb19-204" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-205"><a href="#cb19-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## Datos de panel (longitudinales)</span></span>
<span id="cb19-206"><a href="#cb19-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-207"><a href="#cb19-207" aria-hidden="true" tabindex="-1"></a>Datos sobre **micro-unidades individuales** que se observan a lo largo de **varios períodos**. El rasgo clave es que observamos *cada* micro-unidad en múltiples instantes de tiempo. Si todas las unidades se observan el mismo número de períodos, el panel es **balanceado**.</span>
<span id="cb19-208"><a href="#cb19-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-209"><a href="#cb19-209" aria-hidden="true" tabindex="-1"></a>*Ejemplo:* 1.000 empresas seguidas durante 2010-2024, registrando ventas, empleo y exportaciones de cada empresa en cada año.</span>
<span id="cb19-210"><a href="#cb19-210" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-211"><a href="#cb19-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-212"><a href="#cb19-212" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb19-213"><a href="#cb19-213" aria-hidden="true" tabindex="-1"></a><span class="fu">## Panel agrupado (*pooled cross-section*)</span></span>
<span id="cb19-214"><a href="#cb19-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-215"><a href="#cb19-215" aria-hidden="true" tabindex="-1"></a>Conjunto formado por la **unión de varias secciones cruzadas** independientes, recogidas en distintos períodos. **No** se siguen las mismas unidades: cada período aporta una muestra nueva. Permite analizar cambios poblacionales a lo largo del tiempo aunque no permite seguir trayectorias individuales.</span>
<span id="cb19-216"><a href="#cb19-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-217"><a href="#cb19-217" aria-hidden="true" tabindex="-1"></a>*Ejemplo:* unir varias olas de la EPA, donde cada trimestre se extrae una muestra fresca de hogares.</span>
<span id="cb19-218"><a href="#cb19-218" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-219"><a href="#cb19-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-220"><a href="#cb19-220" aria-hidden="true" tabindex="-1"></a>:::{.callout-warning}</span>
<span id="cb19-221"><a href="#cb19-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## Error frecuente</span></span>
<span id="cb19-222"><a href="#cb19-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-223"><a href="#cb19-223" aria-hidden="true" tabindex="-1"></a>No confundir **panel** con **panel agrupado**: la diferencia clave es si las **mismas** unidades se siguen a lo largo del tiempo (panel) o si se extraen **muestras nuevas** en cada período (panel agrupado).</span>
<span id="cb19-224"><a href="#cb19-224" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-225"><a href="#cb19-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-226"><a href="#cb19-226" aria-hidden="true" tabindex="-1"></a><span class="fu">## Práctica: exploración de datos económicos en R</span></span>
<span id="cb19-227"><a href="#cb19-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-228"><a href="#cb19-228" aria-hidden="true" tabindex="-1"></a>En esta práctica usaremos el conjunto de datos <span class="in">`wage1`</span> del paquete <span class="in">`wooldridge`</span>, que contiene información de 526 trabajadores estadounidenses en mayo de 1976 (corte transversal). El objetivo es **explorar** los datos antes de cualquier modelización: calcular medias y medianas, visualizar distribuciones y obtener **medias condicionales** que ilustren —pero no demuestren— posibles relaciones.</span>
<span id="cb19-229"><a href="#cb19-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-230"><a href="#cb19-230" aria-hidden="true" tabindex="-1"></a>Si es la primera vez que se usa el paquete <span class="in">`wooldridge`</span>, hay que instalarlo desde la consola de R con <span class="in">`install.packages("wooldridge")`</span>. La instalación se hace **una sola vez**; cargar el paquete con <span class="in">`library()`</span> se hace en cada sesión.</span>
<span id="cb19-231"><a href="#cb19-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-234"><a href="#cb19-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-235"><a href="#cb19-235" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb19-236"><a href="#cb19-236" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb19-237"><a href="#cb19-237" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb19-238"><a href="#cb19-238" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span>
<span id="cb19-239"><a href="#cb19-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-240"><a href="#cb19-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-241"><a href="#cb19-241" aria-hidden="true" tabindex="-1"></a><span class="fu">### Estructura del conjunto de datos</span></span>
<span id="cb19-242"><a href="#cb19-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-245"><a href="#cb19-245" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-246"><a href="#cb19-246" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wage1)</span>
<span id="cb19-247"><a href="#cb19-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-248"><a href="#cb19-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-249"><a href="#cb19-249" aria-hidden="true" tabindex="-1"></a>Cada fila representa **un trabajador** observado **una sola vez** en mayo de 1976. No hay índice temporal ni identificadores individuales repetidos: estamos ante un **corte transversal**, no un panel.</span>
<span id="cb19-250"><a href="#cb19-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-251"><a href="#cb19-251" aria-hidden="true" tabindex="-1"></a><span class="fu">### Estadísticas descriptivas</span></span>
<span id="cb19-252"><a href="#cb19-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-255"><a href="#cb19-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-256"><a href="#cb19-256" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"tenure"</span>)])</span>
<span id="cb19-257"><a href="#cb19-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-258"><a href="#cb19-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-259"><a href="#cb19-259" aria-hidden="true" tabindex="-1"></a>Las variables principales son:</span>
<span id="cb19-260"><a href="#cb19-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-261"><a href="#cb19-261" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`wage`</span>: salario por hora en dólares de 1976.</span>
<span id="cb19-262"><a href="#cb19-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`educ`</span>: años de educación.</span>
<span id="cb19-263"><a href="#cb19-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`exper`</span>: años de experiencia laboral potencial.</span>
<span id="cb19-264"><a href="#cb19-264" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`tenure`</span>: años de antigüedad en el empleo actual.</span>
<span id="cb19-265"><a href="#cb19-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-268"><a href="#cb19-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-269"><a href="#cb19-269" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"female"</span>, <span class="st">"married"</span>)])</span>
<span id="cb19-270"><a href="#cb19-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-271"><a href="#cb19-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-272"><a href="#cb19-272" aria-hidden="true" tabindex="-1"></a><span class="fu">### Distribuciones</span></span>
<span id="cb19-273"><a href="#cb19-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-276"><a href="#cb19-276" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-277"><a href="#cb19-277" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribución del salario por hora (USD)."</span></span>
<span id="cb19-278"><a href="#cb19-278" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>wage,</span>
<span id="cb19-279"><a href="#cb19-279" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb19-280"><a href="#cb19-280" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribución del salario por hora"</span>,</span>
<span id="cb19-281"><a href="#cb19-281" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Salario (USD/h)"</span>)</span>
<span id="cb19-282"><a href="#cb19-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-283"><a href="#cb19-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-284"><a href="#cb19-284" aria-hidden="true" tabindex="-1"></a>La distribución del salario es claramente **asimétrica a la derecha**: la media (aproximadamente 5,90 USD/h) es mayor que la mediana (4,65 USD/h), lo que indica una cola larga de salarios altos. Es un patrón habitual en datos de renta y salarios.</span>
<span id="cb19-285"><a href="#cb19-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-288"><a href="#cb19-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-289"><a href="#cb19-289" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribución de los años de educación."</span></span>
<span id="cb19-290"><a href="#cb19-290" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb19-291"><a href="#cb19-291" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">18</span>, <span class="at">col =</span> <span class="st">"lightgreen"</span>,</span>
<span id="cb19-292"><a href="#cb19-292" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Años de educación"</span>,</span>
<span id="cb19-293"><a href="#cb19-293" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>)</span>
<span id="cb19-294"><a href="#cb19-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-295"><a href="#cb19-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-296"><a href="#cb19-296" aria-hidden="true" tabindex="-1"></a><span class="fu">### Diagrama de dispersión: salario frente a educación</span></span>
<span id="cb19-297"><a href="#cb19-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-300"><a href="#cb19-300" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-301"><a href="#cb19-301" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Salario por hora frente a años de educación. La línea roja es el ajuste por MCO."</span></span>
<span id="cb19-302"><a href="#cb19-302" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>wage,</span>
<span id="cb19-303"><a href="#cb19-303" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.3</span>),</span>
<span id="cb19-304"><a href="#cb19-304" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>,</span>
<span id="cb19-305"><a href="#cb19-305" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Salario por hora (USD)"</span>,</span>
<span id="cb19-306"><a href="#cb19-306" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Salario vs. educación"</span>)</span>
<span id="cb19-307"><a href="#cb19-307" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(wage <span class="sc">~</span> educ, <span class="at">data =</span> wage1), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb19-308"><a href="#cb19-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-309"><a href="#cb19-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-312"><a href="#cb19-312" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-313"><a href="#cb19-313" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ)</span>
<span id="cb19-314"><a href="#cb19-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-315"><a href="#cb19-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-316"><a href="#cb19-316" aria-hidden="true" tabindex="-1"></a>La correlación entre salario y educación es aproximadamente **0,41**: positiva, como esperaríamos. Pero conviene ser cauto en la interpretación:</span>
<span id="cb19-317"><a href="#cb19-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-318"><a href="#cb19-318" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>La nube muestra **heterocedasticidad**: la varianza del salario es mucho mayor para niveles altos de educación que para niveles bajos (volveremos sobre esto en el Capítulo 7).</span>
<span id="cb19-319"><a href="#cb19-319" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>La correlación **no es** el efecto causal de la educación sobre el salario. Las personas con más años de estudios difieren en habilidad innata, motivación, origen familiar y muchas otras dimensiones que también están en $u$.</span>
<span id="cb19-320"><a href="#cb19-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-321"><a href="#cb19-321" aria-hidden="true" tabindex="-1"></a><span class="fu">### Medias condicionales</span></span>
<span id="cb19-322"><a href="#cb19-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-323"><a href="#cb19-323" aria-hidden="true" tabindex="-1"></a>Una forma rápida de detectar asociaciones brutas es calcular la **media de $Y$ por grupos** definidos por una variable categórica. En R lo hacemos con <span class="in">`tapply()`</span>.</span>
<span id="cb19-324"><a href="#cb19-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-327"><a href="#cb19-327" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-328"><a href="#cb19-328" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por género (female = 1 si mujer)</span></span>
<span id="cb19-329"><a href="#cb19-329" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>female, mean)</span>
<span id="cb19-330"><a href="#cb19-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-331"><a href="#cb19-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-334"><a href="#cb19-334" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-335"><a href="#cb19-335" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por estado civil</span></span>
<span id="cb19-336"><a href="#cb19-336" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>married, mean)</span>
<span id="cb19-337"><a href="#cb19-337" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-338"><a href="#cb19-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-341"><a href="#cb19-341" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-342"><a href="#cb19-342" aria-hidden="true" tabindex="-1"></a><span class="co"># Salario medio por intervalos de educación</span></span>
<span id="cb19-343"><a href="#cb19-343" aria-hidden="true" tabindex="-1"></a>wage1<span class="sc">$</span>educ_grupo <span class="ot">&lt;-</span> <span class="fu">cut</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb19-344"><a href="#cb19-344" aria-hidden="true" tabindex="-1"></a>                        <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">18</span>),</span>
<span id="cb19-345"><a href="#cb19-345" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Hasta 8"</span>, <span class="st">"9-12"</span>, <span class="st">"13-16"</span>, <span class="st">"17+"</span>))</span>
<span id="cb19-346"><a href="#cb19-346" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ_grupo, mean)</span>
<span id="cb19-347"><a href="#cb19-347" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-348"><a href="#cb19-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-349"><a href="#cb19-349" aria-hidden="true" tabindex="-1"></a>Estos números son **medias condicionales**, no efectos causales. La brecha salarial bruta entre hombres y mujeres (aproximadamente 7,10 vs. 4,59 USD/h) refleja diferencias en ocupación, experiencia, sector, horas, decisiones de fecundidad, posible discriminación, etc. Para interpretarlas como efectos *ceteris paribus* necesitaremos una **regresión múltiple** que mantenga fijos los confusores observables (Capítulo 3).</span>
<span id="cb19-350"><a href="#cb19-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-351"><a href="#cb19-351" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip collapse="true"}</span>
<span id="cb19-352"><a href="#cb19-352" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pista: ¿qué pasa si estimamos un MCO simple aquí?</span></span>
<span id="cb19-353"><a href="#cb19-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-354"><a href="#cb19-354" aria-hidden="true" tabindex="-1"></a>Es perfectamente posible escribir <span class="in">`summary(lm(wage ~ educ, data = wage1))`</span> ahora mismo. Pero la interpretación del coeficiente como «retorno causal de un año de educación» exige supuestos fuertes (no SVO, no sesgo de selección). En el Capítulo 2 estimaremos este modelo con cuidado; en el Capítulo 3 introduciremos controles.</span>
<span id="cb19-355"><a href="#cb19-355" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-356"><a href="#cb19-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-357"><a href="#cb19-357" aria-hidden="true" tabindex="-1"></a><span class="fu">## Auto-evaluación {.unnumbered}</span></span>
<span id="cb19-358"><a href="#cb19-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-359"><a href="#cb19-359" aria-hidden="true" tabindex="-1"></a>Ocho preguntas breves de opción múltiple. Intenta responder cada una antes de desplegar la solución.</span>
<span id="cb19-360"><a href="#cb19-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-361"><a href="#cb19-361" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-362"><a href="#cb19-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q1. ¿Qué es un modelo econométrico?</span></span>
<span id="cb19-363"><a href="#cb19-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-364"><a href="#cb19-364" aria-hidden="true" tabindex="-1"></a>Un modelo econométrico se diferencia de un modelo económico puramente teórico en que:</span>
<span id="cb19-365"><a href="#cb19-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-366"><a href="#cb19-366" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Supone que la relación entre variables es exacta y determinista.</span>
<span id="cb19-367"><a href="#cb19-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Añade un término de error estocástico y una forma funcional, de modo que los parámetros desconocidos puedan estimarse a partir de datos.</span>
<span id="cb19-368"><a href="#cb19-368" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. No necesita una muestra de datos porque los parámetros se derivan de la teoría.</span>
<span id="cb19-369"><a href="#cb19-369" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Solo se utiliza en problemas macroeconómicos, no en microeconómicos.</span>
<span id="cb19-370"><a href="#cb19-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-371"><a href="#cb19-371" aria-hidden="true" tabindex="-1"></a>**Respuesta: B.** Un modelo econométrico combina una forma funcional con una perturbación aleatoria $u$, lo que permite estimar los parámetros desconocidos a partir de los datos observados.</span>
<span id="cb19-372"><a href="#cb19-372" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-373"><a href="#cb19-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-374"><a href="#cb19-374" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-375"><a href="#cb19-375" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q2. El papel del término de error</span></span>
<span id="cb19-376"><a href="#cb19-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-377"><a href="#cb19-377" aria-hidden="true" tabindex="-1"></a>En el modelo de regresión poblacional $y = \beta_0 + \beta_1 x + u$, el término de error $u$:</span>
<span id="cb19-378"><a href="#cb19-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-379"><a href="#cb19-379" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Es la diferencia entre $y_i$ y el valor ajustado por MCO $\hat{y}_i$ en nuestra muestra.</span>
<span id="cb19-380"><a href="#cb19-380" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Es siempre igual a cero en la población.</span>
<span id="cb19-381"><a href="#cb19-381" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Recoge todos los factores —distintos de $x$— que influyen sobre $y$.</span>
<span id="cb19-382"><a href="#cb19-382" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Es observable tan pronto como disponemos de datos de $y$ y $x$.</span>
<span id="cb19-383"><a href="#cb19-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-384"><a href="#cb19-384" aria-hidden="true" tabindex="-1"></a>**Respuesta: C.** $u$ es una magnitud *poblacional* y *no observable* que agrupa todos los determinantes omitidos de $y$. El residuo $\hat{u}_i$ es su análogo muestral, calculado solo tras la estimación.</span>
<span id="cb19-385"><a href="#cb19-385" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-386"><a href="#cb19-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-387"><a href="#cb19-387" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-388"><a href="#cb19-388" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q3. ¿Corte transversal o no?</span></span>
<span id="cb19-389"><a href="#cb19-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-390"><a href="#cb19-390" aria-hidden="true" tabindex="-1"></a>Un conjunto de datos con información sobre 526 trabajadores entrevistados en mayo de 1976 (una observación por trabajador, todos medidos en el mismo instante) es:</span>
<span id="cb19-391"><a href="#cb19-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-392"><a href="#cb19-392" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Datos de corte transversal.</span>
<span id="cb19-393"><a href="#cb19-393" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Datos de series temporales.</span>
<span id="cb19-394"><a href="#cb19-394" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Datos de panel (longitudinales).</span>
<span id="cb19-395"><a href="#cb19-395" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Panel agrupado.</span>
<span id="cb19-396"><a href="#cb19-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-397"><a href="#cb19-397" aria-hidden="true" tabindex="-1"></a>**Respuesta: A.** Muchas unidades, un único período, sin observaciones repetidas de la misma unidad: la definición estándar de corte transversal.</span>
<span id="cb19-398"><a href="#cb19-398" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-399"><a href="#cb19-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-400"><a href="#cb19-400" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-401"><a href="#cb19-401" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q4. Series temporales</span></span>
<span id="cb19-402"><a href="#cb19-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-403"><a href="#cb19-403" aria-hidden="true" tabindex="-1"></a>Las tasas anuales de paro en España de 1980 a 2024 son un ejemplo de:</span>
<span id="cb19-404"><a href="#cb19-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-405"><a href="#cb19-405" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Datos de corte transversal.</span>
<span id="cb19-406"><a href="#cb19-406" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Datos de series temporales.</span>
<span id="cb19-407"><a href="#cb19-407" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Datos de panel.</span>
<span id="cb19-408"><a href="#cb19-408" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Datos experimentales.</span>
<span id="cb19-409"><a href="#cb19-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-410"><a href="#cb19-410" aria-hidden="true" tabindex="-1"></a>**Respuesta: B.** Una única magnitud (la tasa de paro) registrada a una frecuencia regular en el tiempo.</span>
<span id="cb19-411"><a href="#cb19-411" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-412"><a href="#cb19-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-413"><a href="#cb19-413" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-414"><a href="#cb19-414" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q5. Panel frente a panel agrupado</span></span>
<span id="cb19-415"><a href="#cb19-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-416"><a href="#cb19-416" aria-hidden="true" tabindex="-1"></a>Una base de datos sigue a 1.000 empresas durante los años 2010-2024, registrando las ventas, el empleo y las exportaciones de cada empresa en cada año. Esto es:</span>
<span id="cb19-417"><a href="#cb19-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-418"><a href="#cb19-418" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Datos de corte transversal, ya que cada fila es un par empresa-año.</span>
<span id="cb19-419"><a href="#cb19-419" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Panel agrupado, ya que se muestrean unidades distintas en cada período.</span>
<span id="cb19-420"><a href="#cb19-420" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Datos de series temporales, ya que tiene una dimensión temporal.</span>
<span id="cb19-421"><a href="#cb19-421" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Datos de panel (longitudinales): las mismas unidades observadas repetidamente a lo largo del tiempo.</span>
<span id="cb19-422"><a href="#cb19-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-423"><a href="#cb19-423" aria-hidden="true" tabindex="-1"></a>**Respuesta: D.** Las mismas empresas se siguen a lo largo de varios períodos, que es exactamente la estructura de panel.</span>
<span id="cb19-424"><a href="#cb19-424" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-425"><a href="#cb19-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-426"><a href="#cb19-426" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-427"><a href="#cb19-427" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q6. ¿Qué nos dice la correlación?</span></span>
<span id="cb19-428"><a href="#cb19-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-429"><a href="#cb19-429" aria-hidden="true" tabindex="-1"></a>Una correlación positiva alta entre dos variables $X$ e $Y$ implica que:</span>
<span id="cb19-430"><a href="#cb19-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-431"><a href="#cb19-431" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. $X$ causa $Y$.</span>
<span id="cb19-432"><a href="#cb19-432" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. $Y$ causa $X$.</span>
<span id="cb19-433"><a href="#cb19-433" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Existe una relación lineal determinista entre ambas.</span>
<span id="cb19-434"><a href="#cb19-434" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Tienden a moverse juntas, pero esta asociación puede deberse a una tercera variable, a causalidad inversa o a sesgo de selección.</span>
<span id="cb19-435"><a href="#cb19-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-436"><a href="#cb19-436" aria-hidden="true" tabindex="-1"></a>**Respuesta: D.** La correlación no dice nada sobre la dirección causal ni sobre la presencia de confusores. El ejemplo de los helados y los ahogamientos del §1.4.2 es la advertencia canónica.</span>
<span id="cb19-437"><a href="#cb19-437" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-438"><a href="#cb19-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-439"><a href="#cb19-439" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-440"><a href="#cb19-440" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q7. Sesgo de selección</span></span>
<span id="cb19-441"><a href="#cb19-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-442"><a href="#cb19-442" aria-hidden="true" tabindex="-1"></a>El sesgo de selección aparece cuando:</span>
<span id="cb19-443"><a href="#cb19-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-444"><a href="#cb19-444" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Las unidades que se «seleccionan» en el grupo de tratamiento difieren sistemáticamente de las que no, incluso antes del tratamiento.</span>
<span id="cb19-445"><a href="#cb19-445" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. El investigador elige los regresores en función de los estadísticos $t$.</span>
<span id="cb19-446"><a href="#cb19-446" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. El tamaño muestral es demasiado pequeño para detectar un efecto verdadero.</span>
<span id="cb19-447"><a href="#cb19-447" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. La variable dependiente se mide con error.</span>
<span id="cb19-448"><a href="#cb19-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-449"><a href="#cb19-449" aria-hidden="true" tabindex="-1"></a>**Respuesta: A.** El sesgo de selección es una propiedad de la *asignación* del tratamiento, no de la estimación ni de la medición. El ejemplo de los respiradores del §1.4.1 es el prototipo.</span>
<span id="cb19-450"><a href="#cb19-450" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-451"><a href="#cb19-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-452"><a href="#cb19-452" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-453"><a href="#cb19-453" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q8. La aleatorización como remedio</span></span>
<span id="cb19-454"><a href="#cb19-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-455"><a href="#cb19-455" aria-hidden="true" tabindex="-1"></a>¿En cuál de los siguientes diseños la aleatorización elimina *por construcción* el sesgo de selección?</span>
<span id="cb19-456"><a href="#cb19-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-457"><a href="#cb19-457" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Comparar individuos empleados frente a desempleados utilizando datos de encuesta de corte transversal.</span>
<span id="cb19-458"><a href="#cb19-458" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Un Ensayo Controlado Aleatorizado (ECA) en el que el tratamiento se asigna por sorteo.</span>
<span id="cb19-459"><a href="#cb19-459" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Comparar estudiantes que eligieron matricularse en una escuela privada frente a una pública.</span>
<span id="cb19-460"><a href="#cb19-460" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Comparar países que adoptaron el euro frente a países que no lo hicieron.</span>
<span id="cb19-461"><a href="#cb19-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-462"><a href="#cb19-462" aria-hidden="true" tabindex="-1"></a>**Respuesta: B.** Solo la asignación aleatoria garantiza que, *en media*, las unidades tratadas y no tratadas tengan las mismas características previas al tratamiento.</span>
<span id="cb19-463"><a href="#cb19-463" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-464"><a href="#cb19-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-465"><a href="#cb19-465" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejercicios {.unnumbered}</span></span>
<span id="cb19-466"><a href="#cb19-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-467"><a href="#cb19-467" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.1 ★ --- Clasificación de conjuntos de datos.** Clasifique cada uno de los siguientes conjuntos de datos como corte transversal, serie temporal, panel o panel agrupado.</span>
<span id="cb19-468"><a href="#cb19-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-469"><a href="#cb19-469" aria-hidden="true" tabindex="-1"></a>(a) IPC mensual español de 1980 a 2024.</span>
<span id="cb19-470"><a href="#cb19-470" aria-hidden="true" tabindex="-1"></a>(b) <span class="in">`wage1`</span>: 526 trabajadores entrevistados en mayo de 1976, una fila por trabajador.</span>
<span id="cb19-471"><a href="#cb19-471" aria-hidden="true" tabindex="-1"></a>(c) La EPA española: cada trimestre se extrae una muestra independiente nueva de hogares (no se vuelve a entrevistar a ningún hogar); después se apilan varios trimestres.</span>
<span id="cb19-472"><a href="#cb19-472" aria-hidden="true" tabindex="-1"></a>(d) Un conjunto de datos que sigue a los mismos 800 estudiantes desde los 6 hasta los 18 años, registrando sus puntuaciones cada año.</span>
<span id="cb19-473"><a href="#cb19-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-474"><a href="#cb19-474" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-475"><a href="#cb19-475" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mostrar solución</span></span>
<span id="cb19-476"><a href="#cb19-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-477"><a href="#cb19-477" aria-hidden="true" tabindex="-1"></a>(a) Serie temporal. (b) Corte transversal. (c) Panel agrupado --- unidades nuevas en cada período. (d) Panel: las *mismas* unidades se siguen a lo largo de varios períodos.</span>
<span id="cb19-478"><a href="#cb19-478" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-479"><a href="#cb19-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-480"><a href="#cb19-480" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.2 ★ --- Detectar sesgo de selección.** Para cada escenario, indique si el sesgo de selección es un problema probable e identifique qué característica lo origina.</span>
<span id="cb19-481"><a href="#cb19-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-482"><a href="#cb19-482" aria-hidden="true" tabindex="-1"></a>(a) Un hospital compara la mortalidad de los pacientes que recibieron respirador con la de los pacientes que no lo recibieron.</span>
<span id="cb19-483"><a href="#cb19-483" aria-hidden="true" tabindex="-1"></a>(b) Un economista compara los salarios de los trabajadores que completaron un programa de formación laboral con los salarios de los trabajadores que no se inscribieron.</span>
<span id="cb19-484"><a href="#cb19-484" aria-hidden="true" tabindex="-1"></a>(c) Unos investigadores comparan los países que adoptaron el euro en 1999 con los países que no lo hicieron.</span>
<span id="cb19-485"><a href="#cb19-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-486"><a href="#cb19-486" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb19-487"><a href="#cb19-487" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mostrar solución</span></span>
<span id="cb19-488"><a href="#cb19-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-489"><a href="#cb19-489" aria-hidden="true" tabindex="-1"></a>(a) Sí --- la gravedad de la enfermedad determina tanto la asignación del respirador como la mortalidad. (b) Sí --- la autoselección hacia la formación viene impulsada por la motivación, los ingresos previos y las perspectivas en el mercado laboral, todo lo cual también afecta al salario. (c) Sí --- los países que se unieron al euro fueron elegidos en función de fundamentos macroeconómicos (los criterios de Maastricht), por lo que no son una muestra aleatoria de países europeos.</span>
<span id="cb19-490"><a href="#cb19-490" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-491"><a href="#cb19-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-492"><a href="#cb19-492" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.3 ★★ --- Signo del sesgo de variable omitida.** Suponga que regresa el salario por hora sobre los años de educación en una muestra de adultos actualmente empleados, *sin* controlar por la habilidad innata. Suponga que (i) los trabajadores más hábiles ganan más, manteniendo fija la educación, y (ii) los trabajadores más hábiles tienden a adquirir más educación. ¿Estará el coeficiente de <span class="in">`educ`</span> sesgado al alza (demasiado positivo) o a la baja (demasiado negativo)? Explique en una frase.</span>
<span id="cb19-493"><a href="#cb19-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-494"><a href="#cb19-494" aria-hidden="true" tabindex="-1"></a>*La solución completa se ofrece en la Edición del Profesor.*</span>
<span id="cb19-495"><a href="#cb19-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-496"><a href="#cb19-496" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.4 ★★ --- Diseño de un experimento aleatorizado.** Desea saber si un curso gratuito de preparación para la universidad (el tratamiento) eleva causalmente la probabilidad de que los estudiantes de secundaria de familias con renta baja se matriculen en la universidad. Esboce el diseño de un experimento aleatorizado que permita identificar este efecto causal. Sea explícito en cuanto a: la población, la regla de asignación, los grupos de tratamiento y control, la variable de resultado y el horizonte temporal. Discuta brevemente una objeción ética que su diseño deberá abordar.</span>
<span id="cb19-497"><a href="#cb19-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-498"><a href="#cb19-498" aria-hidden="true" tabindex="-1"></a>*La solución completa se ofrece en la Edición del Profesor.*</span>
<span id="cb19-499"><a href="#cb19-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-500"><a href="#cb19-500" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.5 ★★ --- Un modelo ingenuo con variable omitida.** El salario de un trabajador se genera mediante</span>
<span id="cb19-501"><a href="#cb19-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-502"><a href="#cb19-502" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-503"><a href="#cb19-503" aria-hidden="true" tabindex="-1"></a>w = 5 + 2 \cdot \mathit{edu} + u, \qquad \mathbb{E}<span class="co">[</span><span class="ot">u</span><span class="co">]</span> = 0,\ \operatorname{Var}(u) = 1,</span>
<span id="cb19-504"><a href="#cb19-504" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb19-505"><a href="#cb19-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-506"><a href="#cb19-506" aria-hidden="true" tabindex="-1"></a>donde $\mathit{edu}\in<span class="sc">\{</span>0,1,2,3<span class="sc">\}</span>$ son los años de educación postobligatoria. Suponga que la habilidad (recogida en $u$) está correlacionada con la educación: $\mathbb{E}<span class="co">[</span><span class="ot">u\mid \mathit{edu}</span><span class="co">]</span> = 0{,}5\cdot \mathit{edu}$.</span>
<span id="cb19-507"><a href="#cb19-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-508"><a href="#cb19-508" aria-hidden="true" tabindex="-1"></a>(a) Calcule $\mathbb{E}<span class="co">[</span><span class="ot">w\mid \mathit{edu}</span><span class="co">]</span>$.</span>
<span id="cb19-509"><a href="#cb19-509" aria-hidden="true" tabindex="-1"></a>(b) Si ingenuamente suponemos $\mathbb{E}<span class="co">[</span><span class="ot">u\mid \mathit{edu}</span><span class="co">]</span> = 0$ y leemos la pendiente, ¿qué obtenemos? ¿En cuánto nos *desviamos* del verdadero efecto marginal de un año adicional de educación?</span>
<span id="cb19-510"><a href="#cb19-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-511"><a href="#cb19-511" aria-hidden="true" tabindex="-1"></a>*La solución completa se ofrece en la Edición del Profesor.*</span>
<span id="cb19-512"><a href="#cb19-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-513"><a href="#cb19-513" aria-hidden="true" tabindex="-1"></a>**Ejercicio 1.6 ★★★ --- Chocolate y premios Nobel.** Se ha documentado <span class="co">[</span><span class="ot">@cgl2017</span><span class="co">]</span> que los países con mayor consumo de chocolate per cápita también ganan más premios Nobel per cápita. ¿Es esto evidencia de que el consumo de chocolate *causa* premios Nobel? Identifique (i) al menos una variable omitida plausible, (ii) al menos un canal causal alternativo (causalidad inversa, selección de los países que se miden, etc.) y (iii) describa un diseño de investigación *hipotético* --- experimental o cuasi-experimental --- que le permitiera conocer el efecto causal del chocolate sobre la obtención de premios. Sea sincero respecto a por qué es poco probable que este diseño sea factible.</span>
<span id="cb19-514"><a href="#cb19-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-515"><a href="#cb19-515" aria-hidden="true" tabindex="-1"></a>*La solución completa se ofrece en la Edición del Profesor.*</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>